@startuml
'https://plantuml.com/class-diagram

class Player
class Board
class Space
class CommandCard


Player "2..6"--"1" Board
Space "1"--"0..1" Player
Space "130"--" 1" Board
Player "1"--"8" CommandCard
Laser--|>Space
Gears--|>Space
EnergySpace--|>Space
PushPanel--|>Space



@enduml